language: python

python:
  - 2.7
  - pypy

env:
  - DJANGO=1.8.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=jssor setup.py test jssor
  #python setup.py test

after_success:
  coveralls
