# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jssor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slideshow_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jssor.ResponsiveGroup')),
            ],
        ),
    ]
